# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/digestion_rates',
                'doc_host': 'https://eugimarine.github.io',
                'git_url': 'https://github.com/eugimarine/digestion_rates',
                'lib_path': 'digestion_rates'},
  'syms': { 'digestion_rates.core': { 'digestion_rates.core.foo': ( 'https://eugimarine.github.io/core.html#foo',
                                                                    'https://github.com/eugimarine/digestion_rates/blob/master/digestion_rates/core.py#L7')}}}