# AUTOGENERATED! DO NOT EDIT! File to edit: ../03_Boostrap_correlation.ipynb.

# %% auto 0
__all__ = ['sample_cells', 'digestion_profile_matrix', 'bootstrap_population', 'correlate_sequence',
           'cross_correlation_on_all_sequences', 'average_results_bootstrap', 'single_iteration_bootstrap_cc',
           'iter_bootstrap_cc']

# %% ../03_Boostrap_correlation.ipynb 4
import pandas as pd
import numpy as np
from scipy.signal import correlate

# %% ../03_Boostrap_correlation.ipynb 10
def sample_cells(df, n_sample):
    selected_cells = np.random.choice(df.cb_encode.unique(), size=n_sample)
    subsampled_df = df.set_index('cb_encode').loc[selected_cells,:].reset_index()
    return subsampled_df


# %% ../03_Boostrap_correlation.ipynb 12
def digestion_profile_matrix(df, aggregation='mean'):
    averages = df.groupby(['seq','log_units_mnase']).aggregate(aggregation).reset_index()
    averages = averages.sort_values('log_units_mnase').reset_index(drop=True)
    dig_matrix = averages.pivot(index='seq', columns='log_units_mnase', values='counts').fillna(0)
    return dig_matrix


# %% ../03_Boostrap_correlation.ipynb 15
def bootstrap_population(seqcell, pop, samples_bootstrap):
    all_g0 = seqcell.loc[seqcell['sort_population']==pop]
    g0_boot = sample_cells(all_g0, samples_bootstrap)
    g0_digprof = digestion_profile_matrix(g0_boot)
    return g0_digprof

# %% ../03_Boostrap_correlation.ipynb 16
def correlate_sequence(row, other, seq_name):
    try:
        other_row = other.loc[seq_name, :]
        cc = correlate(row, other_row, "full")
        return cc
    except KeyError:
        return np.array([np.nan] * 27)

# %% ../03_Boostrap_correlation.ipynb 18
def cross_correlation_on_all_sequences(g0_profile, inter_profile):
    corr_df_shape = (g0_profile.shape[0], g0_profile.shape[1]*2-1)
    range_values = (-1*(g0_profile.shape[1]-1), g0_profile.shape[1] )
    corr_df = pd.DataFrame(np.zeros(corr_df_shape), index=g0_profile.index, columns=list(range(*range_values)))

    for nm,row in g0_profile.iterrows():
        corr = correlate_sequence(row, inter_profile, nm)
        corr_df.loc[nm, :] = corr
    corr_df = corr_df.dropna()
    return corr_df


# %% ../03_Boostrap_correlation.ipynb 21
def average_results_bootstrap(cross_correlations):
    cat_correlations = pd.concat(cross_correlations, axis=0, join='inner')
    mean_cc = cat_correlations.groupby(cat_correlations.index).mean()
    se_cc = cat_correlations.groupby(cat_correlations.index).sem()
    max_cc = mean_cc.idxmax(axis = 1)
    return mean_cc, se_cc, max_cc

# %% ../03_Boostrap_correlation.ipynb 23
def single_iteration_bootstrap_cc(seqcell, populations, samples_bootstrap):
    g0_digprof = bootstrap_population(seqcell, populations[0], samples_bootstrap)
    inter_digprof = bootstrap_population(seqcell, populations[1], samples_bootstrap)
    cc = cross_correlation_on_all_sequences(g0_digprof, inter_digprof)
    return cc


# %% ../03_Boostrap_correlation.ipynb 25
def iter_bootstrap_cc(seqcell, populations= [0,1], samples_bootstrap=200, n_iter=100):    
    cross_correlations = []

    for _ in range(n_iter):
        cc = single_iteration_bootstrap_cc(seqcell, populations, samples_bootstrap)
        cross_correlations.append(cc)
        
    return cross_correlations

