# AUTOGENERATED! DO NOT EDIT! File to edit: ../03_Boostrap_correlation.ipynb.

# %% auto 0
__all__ = ['sample_cells', 'digestion_profile_matrix', 'fill_not_found_sequences', 'bootstrap_population', 'correlate_sequence',
           'cross_correlation_on_all_sequences', 'gmean_score', 'single_iteration_bootstrap_cc', 'iter_bootstrap_cc',
           'average_results_bootstrap']

# %% ../03_Boostrap_correlation.ipynb 4
import pandas as pd
import numpy as np
from scipy.signal import correlate

# %% ../03_Boostrap_correlation.ipynb 11
def sample_cells(df, n_sample):
    selected_cells = np.random.choice(df.cb_encode.unique(), size=n_sample)
    subsampled_df = df.set_index('cb_encode').loc[selected_cells,:].reset_index()
    return subsampled_df


# %% ../03_Boostrap_correlation.ipynb 14
def digestion_profile_matrix(df, aggregation='mean'):
    averages = df.groupby(['seq','log_units_mnase']).aggregate(aggregation).reset_index()
    averages = averages.sort_values('log_units_mnase').reset_index(drop=True)
    dig_matrix = averages.pivot(index='seq', columns='log_units_mnase', values='counts').fillna(0)
    return dig_matrix


# %% ../03_Boostrap_correlation.ipynb 17
def fill_not_found_sequences(df, metadata):
    seq_allc, cb_encode_allc = pd.core.reshape.util.cartesian_product([df['seq'].unique(), df['cb_encode'].unique()])
    df_all_comb = pd.DataFrame({'cb_encode':list(cb_encode_allc), 'seq':list(seq_allc)})
    partial = pd.merge(df,df_all_comb, on=['cb_encode', 'seq'], how='outer')
    partial['counts'] = partial['counts'].fillna(0)
    partial = partial.set_index('cb_encode').fillna(metadata.set_index('cb_encode').to_dict()).reset_index()
    return partial

# %% ../03_Boostrap_correlation.ipynb 20
def bootstrap_population(seqcell, pop, samples_size, metadata):
    all_g0 = seqcell.loc[seqcell['sort_population']==pop]
    g0_boot = sample_cells(all_g0, samples_size)
    filled_df = fill_not_found_sequences(g0_boot, metadata)
    g0_digprof = digestion_profile_matrix(g0_boot)
    return g0_digprof

# %% ../03_Boostrap_correlation.ipynb 22
def correlate_sequence(row, other, seq_name):
    try:
        other_row = other.loc[seq_name, :]
        cc = correlate(row, other_row, "full")
        return cc
    except KeyError:
        return np.array([np.nan] * other.shape[1]*2-1)

# %% ../03_Boostrap_correlation.ipynb 25
def cross_correlation_on_all_sequences(g0_profile, inter_profile):
    corr_df_shape = (g0_profile.shape[0], g0_profile.shape[1]*2-1)
    range_values = (-1*(g0_profile.shape[1]-1), g0_profile.shape[1] )
    corr_df = pd.DataFrame(np.zeros(corr_df_shape), index=g0_profile.index, columns=list(range(*range_values)))

    for nm,row in g0_profile.iterrows():
        corr = correlate_sequence(row, inter_profile, nm)
        corr_df.loc[nm, :] = corr
    corr_df = corr_df.dropna()
    return corr_df


# %% ../03_Boostrap_correlation.ipynb 29
def gmean_score(pop1_digmatrix, pop2_digmatrix, threshold):
    gm_score = (pop1_digmatrix.aggregate('mean', axis=1) * pop2_digmatrix.aggregate('mean', axis=1)).dropna()
    i = gm_score.index[gm_score>threshold]
    return gm_score, i
    

# %% ../03_Boostrap_correlation.ipynb 32
def single_iteration_bootstrap_cc(seqcell, populations, samples_bootstrap, metadata, threshold=1):
    g0_digprof = bootstrap_population(seqcell, populations[0], samples_bootstrap, metadata)
    inter_digprof = bootstrap_population(seqcell, populations[1], samples_bootstrap, metadata)
    # filter low mean counts
    gmean, idx = gmean_score(g0_digprof, inter_digprof, threshold=threshold)
    g0_digprof = g0_digprof.loc[idx, :]
    inter_digprof = inter_digprof.loc[idx, :]
    
    cc = cross_correlation_on_all_sequences(g0_digprof, inter_digprof)
    return cc


# %% ../03_Boostrap_correlation.ipynb 35
def iter_bootstrap_cc(seqcell, populations= [0,1], samples_bootstrap=200, n_iter=100, apply_filter=True):    
    cross_correlations = []

    for _ in range(n_iter):
        cc = single_iteration_bootstrap_cc(seqcell, populations, samples_bootstrap)
        cross_correlations.append(cc)
        
    return cross_correlations


# %% ../03_Boostrap_correlation.ipynb 36
def average_results_bootstrap(cross_correlations):
    cat_correlations = pd.concat(cross_correlations, axis=0, join='inner')
    mean_cc = cat_correlations.groupby(cat_correlations.index).mean()
    se_cc = cat_correlations.groupby(cat_correlations.index).sem()
    max_cc = mean_cc.idxmax(axis = 1)
    return mean_cc, se_cc, max_cc
