# AUTOGENERATED! DO NOT EDIT! File to edit: ../main.ipynb.

# %% auto 0
__all__ = ['main']

# %% ../main.ipynb 4
from .fastq_reader import SequencesCells, FastQ
import sys
import glob

# %% ../main.ipynb 8
def main():
    input_path = sys.argv[1]
    output_path = sys.argv[2]
    plates = None
    for f in glob.glob('.'+'/*.fastq.gz'):
        plate = FastQ(f).parse_file()
        if plates is None:
            plates = plate
            continue
        plates.join_plate(plate)
    plates.table.to_csv(output_path, index_label='sequence', compression='gzip')
    
    
    
    
if __name__ == '__main__':
    main()
