# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_simulations.ipynb.

# %% auto 0
__all__ = []

# %% ../00_simulations.ipynb 3
#| export

# %% ../00_simulations.ipynb 4
import numpy as np
import pandas as pd


# %% ../00_simulations.ipynb 5
class
